site_name: Mountea Framework Docs
site_url: https://mountea.tools/docs/
docs_dir: docs_src
site_dir: docs

theme:
  name: material
  favicon: ../assets/icon.png
  logo: ../assets/icon.png
  palette:
    scheme: slate
    primary: black
    accent: cyan
  features:
    - navigation.instant
    - navigation.sections
    #- navigation.tabs
    - navigation.top
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.tabs.link
    - content.action.edit
    - toc.integrate

nav:
  - Home: index.md
  - Projects:
    - Advanced Inventory & Equipment System:
        - Overview: AdvancedInventoryEquipmentSystem/Overview.md
        - Inventory System:
            - Overview: AdvancedInventoryEquipmentSystem/InventorySystem/InventorySystem.md
            - Inventory Component: AdvancedInventoryEquipmentSystem/InventorySystem/InventoryComponent.md
            - Item Templates: AdvancedInventoryEquipmentSystem/InventorySystem/ItemTemplates.md
            - Item Instances: AdvancedInventoryEquipmentSystem/InventorySystem/ItemInstances.md            
            - Item Actions: AdvancedInventoryEquipmentSystem/InventorySystem/ItemActions.md
            - Categories: AdvancedInventoryEquipmentSystem/InventorySystem/Categories.md
            - Rarity System: AdvancedInventoryEquipmentSystem/InventorySystem/Rarity.md
            - Search & Filtering: AdvancedInventoryEquipmentSystem/InventorySystem/Search.md
            - Notifications: AdvancedInventoryEquipmentSystem/InventorySystem/Notifications.md
        - Equipment System:
            - Overview: AdvancedInventoryEquipmentSystem/EquipmentSystem/EquipmentSystem.md
            - Attachment System: AdvancedInventoryEquipmentSystem/EquipmentSystem/AttachmentSystem.md
        - User Interface:
            - Overview: AdvancedInventoryEquipmentSystem/UserInterface/UserInterface.md
            - Inventory UI: AdvancedInventoryEquipmentSystem/UserInterface/InventoryUI.md
            - Grid System: AdvancedInventoryEquipmentSystem/UserInterface/GridSystem.md
            - Item Widgets: AdvancedInventoryEquipmentSystem/UserInterface/ItemWidgets.md
            - Item Preview: AdvancedInventoryEquipmentSystem/UserInterface/ItemPreview.md
            - Slate Elements: AdvancedInventoryEquipmentSystem/UserInterface/SlateElements.md
        - Configuration:
            - Settings: AdvancedInventoryEquipmentSystem/Configuration/Settings.md
            - Inventory Types: AdvancedInventoryEquipmentSystem/Configuration/InventoryTypes.md
            - Categories & Rarities: AdvancedInventoryEquipmentSystem/Configuration/ItemCategoriesRarities.md
            - UI Theming: AdvancedInventoryEquipmentSystem\Configuration\UIThemingGuide.md
            - Replication: AdvancedInventoryEquipmentSystem/Configuration/Replication.md

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 2
