[build]
  command = "python script/build_combined.py --mode ci --dialoguer-base /dialoguer/app/ --submodule-remote"
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/inventour/app"
  to = "/inventour/app/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/inventour/app/*"
  to = "/inventour/app/index.html"
  status = 200
  force = true
